# With TabbyAPI
FROM dave

ENV MODEL='https://huggingface.co/sleepdeprived3/sleepdeprived3_Reformed-Christian-Bible-Expert-12B_EXL2_5.5bpw_H8'

COPY tabbyAPI ./tabbyAPI
RUN ["sh", "-c", "cd /app/tabbyAPI; python start.py --update-deps << EOF\nA\nEOF"]
COPY config.yml ./tabbyAPI/config.yml
COPY dave_preset.yml ./tabbyAPI/sampler_overrides/

COPY docker/tabby/entrypoint.sh ./
CMD ["./entrypoint.sh"]
